server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PW}@cluster0.ncx8l.mongodb.net/${MONGO_DB}?retryWrites=true&w=majority

